mysql:
  build: ./mysql-emlo
  restart: always

  environment:
    MYSQL_ROOT_PASSWORD: jbnslbsbpsjb

  ports:
    - "3306:3306"

  volumes:
    - ./vol-mysql/data:/var/lib/mysql

omeka:
  build: ./omeka

  environment:
    OMEKA_DB_HOST: mysql
    OMEKA_DB_PORT: 3306
    OMEKA_DB_USER: root
    OMEKA_DB_PASSWORD: jbnslbsbpsjb
    OMEKA_DB_DATABASE: omeka
    OMEKA_DB_PREFIX: omeka_

  ports:
    - "80:80"

  links:
    - mysql


#catalogues:
#  build: ./wp-emlo-catalogues
#
#  ports:
#    - "8080:80"
#
#  links:
#    - mysql

#nginx:
#  build: ./nginx-emlo
#  restart: always
#
#  links:
#    - catalogues
#
#  ports:
#    - "80:80"