# Setup the MYSQL_ROOT_PASSWORD
# export MYSQL_ROOT_PASSWORD="PASSWORD-HERE"
#
mysql:
  build: ./mysql-emlo

  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  ports:
    - "3305:3306"

  volumes:
    - ./vol-mysql/data:/var/lib/mysql

#phpmyadmin:
#  image: phpmyadmin/phpmyadmin:latest
#
#  links:
#    - mysql:db

#  ports:
#    - 8088:80

omk-baxter:
  build: ./omk-baxter

  environment:
    OMEKA_WEB_ROOT: /exhibition/baxter/
    OMEKA_DB_USER: root
    OMEKA_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    OMEKA_DB_PREFIX: omeka_baxter_

  ports:
    - "8082:80"

  links:
    - mysql

  volumes:
    - ./omk-baxter/html:/var/www/html/exhibition/baxter


omk-wemlo:
  build: ./omk-wemlo

  environment:
    OMEKA_WEB_ROOT: /wemlo/
    OMEKA_DB_USER: root
    OMEKA_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    OMEKA_DB_PREFIX: omeka_wemlo_

  ports:
    - "8084:80"

  links:
    - mysql

  volumes:
    - ./omk-wemlo/html:/var/www/html/wemlo

omk-sw:
  build: ./omk-sw

  environment:
    OMEKA_WEB_ROOT: /exhibition/sw/
    OMEKA_DB_USER: root
    OMEKA_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    OMEKA_DB_PREFIX: omeka_sw_

  ports:
    - "8083:80"

  links:
    - mysql

  volumes:
    - ./omk-sw/html:/var/www/html/exhibition/sw


wp-catalogues:
  build: ./wp-emlo-catalogues

  ports:
    - "8081:80"

  links:
    - mysql

  environment:
    WORDPRESS_DB_HOST: mysql
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    WORDPRESS_DB_NAME: wordpress

  volumes:
    - ./wp-emlo-catalogues/wp-catalogues:/var/www/html/collections

nginx:
  build: ./nginx-emlo
  #restart: always

  links:
    - wp-catalogues
    - omk-baxter
    - omk-sw
    - omk-wemlo

  ports:
    - "80:80"