mysql:
  build: ./mysql-emlo
  restart: always

  environment:
    MYSQL_ROOT_PASSWORD: jbnslbsbpsjb

  ports:
    - "3305:3306"

  volumes:
    - ./vol-mysql/data:/var/lib/mysql


omk-baxter:
  build: ./omk-baxter

  environment:
    OMEKA_WEB_ROOT: /baxter/
    OMEKA_DB_USER: root
    OMEKA_DB_PASSWORD: jbnslbsbpsjb
    OMEKA_DB_PREFIX: omeka_baxter_

  ports:
    - "8082:80"

  links:
    - mysql

  volumes:
    - ./omk-baxter/html:/var/www/html/baxter


omk-wemlo:
  build: ./omk-wemlo

  environment:
    OMEKA_WEB_ROOT: /wemlo/
    OMEKA_DB_USER: root
    OMEKA_DB_PASSWORD: jbnslbsbpsjb
    OMEKA_DB_PREFIX: omeka_wemlo_

  ports:
    - "8084:80"

  links:
    - mysql

  volumes:
    - ./omk-wemlo/html:/var/www/html/wemlo

omk-sw:
  build: ./omk-sw

  environment:
    OMEKA_WEB_ROOT: /sw/
    OMEKA_DB_USER: root
    OMEKA_DB_PASSWORD: jbnslbsbpsjb
    OMEKA_DB_PREFIX: omeka_sw_

  ports:
    - "8083:80"

  links:
    - mysql

  volumes:
    - ./omk-sw/html:/var/www/html/sw


#omeka:
#  build: ./omeka
#
#  environment:
#    OMEKA_DB_HOST: mysql
#    OMEKA_DB_PORT: 3306
#    OMEKA_DB_USER: root
#    OMEKA_DB_PASSWORD: jbnslbsbpsjb
#    OMEKA_DB_DATABASE: omeka
#    OMEKA_DB_PREFIX: omeka_
#
#  ports:
#    - "8080:80"
#
#  links:
#    - mysql


wp-catalogues:
  build: ./wp-emlo-catalogues

  ports:
    - "8081:80"

  links:
    - mysql

  environment:
    WORDPRESS_DB_HOST: mysql
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_PASSWORD: jbnslbsbpsjb
    WORDPRESS_DB_NAME: wordpress

  volumes:
    - ./wp-emlo-catalogues/wp-catalogues:/var/www/html

nginx:
  build: ./nginx-emlo
  restart: always

  links:
    - wp-catalogues
    - omk-baxter
    - omk-sw
    - omk-wemlo

  ports:
    - "80:80"