mysql:
  build: ./mysql-emlo
  restart: always

  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  volumes:
    - ./vol-mysql/data:/var/lib/mysql

omk-baxter:
  build: ./omk-baxter
  restart: always

  environment:
    OMEKA_WEB_ROOT: /exhibition/baxter/
    OMEKA_DB_USER: root
    OMEKA_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    OMEKA_DB_PREFIX: omeka_baxter_

  links:
    - mysql

  volumes:
    - ./omk-baxter/html:/var/www/html/exhibition/baxter


omk-wemlo:
  build: ./omk-wemlo
  restart: always

  environment:
    OMEKA_WEB_ROOT: /wemlo/
    OMEKA_DB_USER: root
    OMEKA_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    OMEKA_DB_PREFIX: omeka_wemlo_

  links:
    - mysql

  volumes:
    - ./omk-wemlo/html:/var/www/html/wemlo

omk-sw:
  build: ./omk-sw

  environment:
    OMEKA_WEB_ROOT: /exhibition/sw/
    OMEKA_DB_USER: root
    OMEKA_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    OMEKA_DB_PREFIX: omeka_sw_

  links:
    - mysql

  volumes:
    - ./omk-sw/html:/var/www/html/exhibition/sw


wp-catalogues:
  build: ./wp-emlo-catalogues

  ports:
    - "8081:80"

  links:
    - mysql

  environment:
    WORDPRESS_DB_HOST: mysql
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    WORDPRESS_DB_NAME: wordpress

  volumes:
    - ./wp-emlo-catalogues/wp-catalogues:/var/www/html

nginx:
  build: ./nginx-emlo
  restart: always

  links:
    - wp-catalogues
    - omk-baxter
    - omk-sw
    - omk-wemlo

  ports:
    - "80:80"