mysql:
  build: ./mysql-emlo
  restart: always

  environment:
    MYSQL_ROOT_PASSWORD: jbnslbsbpsjb

  ports:
    - "3306:3306"

  volumes:
    - ./vol-mysql/data:/var/lib/mysql


baxter:
  build: ./omk-baxter

  environment:
    OMEKA_WEB_ROOT: /baxter/
    OMEKA_DB_USER: root
    OMEKA_DB_PASSWORD: jbnslbsbpsjb
    OMEKA_DB_PREFIX: omeka_baxter_

  ports:
    - "8082:80"

  links:
    - mysql

  volumes:
    - ./omk-baxter/html:/var/www/html/baxter


sw:
  build: ./omk-sw

  environment:
    OMEKA_WEB_ROOT: /sw/
    OMEKA_DB_USER: root
    OMEKA_DB_PASSWORD: jbnslbsbpsjb
    OMEKA_DB_PREFIX: omeka_sw_

  ports:
    - "8083:80"

  links:
    - mysql

  volumes:
    - ./omk-sw/html:/var/www/html/sw


#omeka:
#  build: ./omeka
#
#  environment:
#    OMEKA_DB_HOST: mysql
#    OMEKA_DB_PORT: 3306
#    OMEKA_DB_USER: root
#    OMEKA_DB_PASSWORD: jbnslbsbpsjb
#    OMEKA_DB_DATABASE: omeka
#    OMEKA_DB_PREFIX: omeka_
#
#  ports:
#    - "8081:80"
#
#  links:
#    - mysql


catalogues:
  build: ./wp-emlo-catalogues

  ports:
    - "8080:80"

  links:
    - mysql

nginx:
  build: ./nginx-emlo
  restart: always

  links:
    - catalogues
    - baxter
    - sw

  ports:
    - "80:80"